dist: xenial
sudo: required
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  global:
    - DEPLOYMENT=STANDALONE
    - DRIVER_VERSION="stable"
    - ADAPTER_VERSION="^1.0.0"
    - SERVER_DISTRO=ubuntu1604
    - SERVER_VERSION=4.2.0

jobs:
  include:
    # Test against lowest dependencies, including driver and server versions
    - stage: Test
      php: 5.6
      env: DRIVER_VERSION="1.6.7" COMPOSER_FLAGS="--prefer-lowest" SERVER_VERSION="3.6.14"

    # Test against MongoDB 4.0
    - stage: Test
      php: 7.3
      env: SERVER_VERSION="4.0.12"

    # Test sharded cluster functionality
    - stage: Test
      php: 7.3
      env: DEPLOYMENT=SHARDED_CLUSTER_RS
      script:
        - ./vendor/bin/phpunit --group=sharding --coverage-clover=coverage.clover

    # Test on replica sets
    - stage: Test
      php: 7.3
      env: DEPLOYMENT=REPLICASET
      script:
        - ./vendor/bin/phpunit --coverage-clover=coverage.clover

    # Performance tests
    - stage: Performance
      php: 5.6
      script: vendor/bin/phpbench run --report=default --revs=100 --iterations=5 --report=aggregate

    - stage: Performance
      php: 7.3
      script: vendor/bin/phpbench run --report=default --revs=100 --iterations=5 --report=aggregate

install:
  - .travis/setup_mongodb.sh
  - sudo pip install mongo-orchestration
  - sudo mongo-orchestration start
  - .travis/setup_mo.sh
  - composer self-update
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then yes '' | pecl -q install -f mongo-${DRIVER_VERSION}; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then pecl install -f mongodb-${DRIVER_VERSION}; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer config "platform.ext-mongo" "1.6.16" && composer require "alcaeus/mongo-php-adapter=${ADAPTER_VERSION}"; fi
  - composer update ${COMPOSER_FLAGS}
  - export DOCTRINE_MONGODB_SERVER=`cat /tmp/uri.txt`
  - echo $DOCTRINE_MONGODB_SERVER

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
